# Generated by Django 4.1.1 on 2022-09-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos',
            old_name='x1',
            new_name='dato1',
        ),
        migrations.RenameField(
            model_name='datos',
            old_name='x2',
            new_name='dato2',
        ),
        migrations.RenameField(
            model_name='datos',
            old_name='x3',
            new_name='dato3',
        ),
    ]
