# Generated by Django 4.1.1 on 2022-09-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0002_rename_x1_datos_dato1_rename_x2_datos_dato2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='c1',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
